#!/usr/bin/env python3
"""Emit BoTorch/GPyTorch and NumPy references for FortBO to be checked against.

The comparison this feeds is a **correctness gate, not a race**. Wall time
between a Fortran binary and a Python stack measures the stacks; what matters
first is whether FortBO's posterior and acquisition agree with two independent
implementations on the same model. A speed number from a build whose numbers are
wrong is worse than no number.

Everything that could differ is pinned rather than fitted: the kernel, its
hyperparameters, the noise, the observations, the query points, and the
precision. Learning hyperparameters on each side would compare two optimizers
and report the difference as a modelling discrepancy.

Two references, not one. GPyTorch is a mature library and its agreement is
strong evidence; NumPy computes the same closed forms directly from the
definitions in a dozen lines, and its agreement is evidence of a *different*
kind — a shared misunderstanding between two GP libraries would show up against
the direct algebra and not against each other.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np

OUTPUT = Path(__file__).resolve().parent.parent / "fixtures" / "reference_gp.json"

# A second copy, in a form Fortran reads with list-directed input, written into
# FortBO's own test tree. The alternative was a JSON parser in Fortran, or a
# FortBO test that reaches across repositories into this one; the first is a lot
# of code to check a fixture with and the second makes FortBO's suite fail when
# this repository is merely absent. The numbers are identical and this script
# regenerates both, so the checked-in copy cannot drift silently.
FORTRAN_OUTPUT = (
    Path(__file__).resolve().parent.parent.parent
    / "fortbo" / "test" / "fixtures" / "reference_gp.txt"
)


def write_fortran_fixture(payload: dict) -> None:
    lines = [
        "# Generated by fortbo-bench/scripts/emit_reference.py. Do not edit.",
        "# Hyperparameters are what GPyTorch actually held, not what it was",
        "# asked for: its constrained setters do not round trip in float64.",
        "# lengthscale signal_variance noise_variance xi",
        f"{payload['lengthscale']!r} {payload['signal_variance']!r} "
        f"{payload['noise_variance']!r} {payload['xi']!r}",
        "# n_train n_query",
        f"{len(payload['train_x'])} {len(payload['query'])}",
    ]
    for name, values in (
        ("train_x", payload["train_x"]),
        ("train_y", payload["train_y"]),
        ("query", payload["query"]),
        ("numpy_mean", payload["numpy"]["mean"]),
        ("numpy_sd", payload["numpy"]["sd"]),
        ("numpy_ei", payload["numpy"]["expected_improvement"]),
    ):
        lines.append(f"# {name}")
        lines.extend(repr(float(v)) for v in values)
    FORTRAN_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    FORTRAN_OUTPUT.write_text("\n".join(lines) + "\n")

# Pinned model. Not fitted: fitting on each side would compare optimizers.
LENGTHSCALE = 0.7
SIGNAL_VARIANCE = 1.3
NOISE_VARIANCE = 0.05
XI = 0.0


def training_set() -> tuple[np.ndarray, np.ndarray]:
    """A deterministic one-dimensional set, stated rather than sampled."""
    x = np.array([[-1.2], [-0.7], [-0.1], [0.35], [0.8], [1.4]], dtype=np.float64)
    y = (np.sin(2.1 * x[:, 0]) + 0.3 * x[:, 0]).astype(np.float64)
    return x, y


def query_set() -> np.ndarray:
    return np.linspace(-1.5, 1.6, 13, dtype=np.float64).reshape(-1, 1)


def rbf(a: np.ndarray, b: np.ndarray, lengthscale: float,
        signal_variance: float) -> np.ndarray:
    """Squared-exponential kernel, written from its definition."""
    squared = (a[:, None, :] - b[None, :, :]) ** 2
    return signal_variance * np.exp(-0.5 * squared.sum(-1) / lengthscale**2)


def numpy_reference(x, y, q, lengthscale, signal_variance, noise) -> dict:
    """Exact GP posterior and expected improvement, direct from the algebra.

    Takes the hyperparameters as arguments rather than reading the constants,
    because GPyTorch cannot be pinned to them exactly and the comparison must
    use whatever it actually holds. See `effective_hyperparameters`.
    """
    def kernel(a, b):
        return rbf(a, b, lengthscale, signal_variance)

    gram = kernel(x, x) + noise * np.eye(len(x))
    factor = np.linalg.cholesky(gram)
    alpha = np.linalg.solve(factor.T, np.linalg.solve(factor, y))

    cross = kernel(x, q)
    mean = cross.T @ alpha
    solved = np.linalg.solve(factor, cross)
    variance = np.diag(kernel(q, q)) - (solved**2).sum(0)
    variance = np.maximum(variance, 0.0)
    sd = np.sqrt(variance)

    # FortBO minimizes, so improvement is over the smallest observed value.
    best = float(y.min())
    gap = best - XI - mean
    with np.errstate(divide="ignore", invalid="ignore"):
        z = np.where(sd > 0.0, gap / np.where(sd > 0.0, sd, 1.0), 0.0)
    cdf = 0.5 * (1.0 + np.vectorize(math.erf)(z / math.sqrt(2.0)))
    pdf = np.exp(-0.5 * z**2) / math.sqrt(2.0 * math.pi)
    ei = np.where(sd > 0.0, gap * cdf + sd * pdf, np.maximum(gap, 0.0))

    return {
        "mean": mean.tolist(),
        "sd": sd.tolist(),
        "expected_improvement": ei.tolist(),
        "best": best,
    }


def botorch_reference(x, y, q) -> dict | None:
    """The same quantities from GPyTorch and BoTorch, with the model pinned.

    BoTorch maximizes, so the objective is negated on the way in and the
    resulting improvement is over `-min(y)`. Getting that wrong would produce a
    reference that disagrees for a reason that is about conventions rather than
    about either implementation, which is the trap this comparison exists to
    avoid.
    """
    try:
        import torch
        from botorch.acquisition.analytic import ExpectedImprovement
        from botorch.models import SingleTaskGP
        from gpytorch.kernels import RBFKernel, ScaleKernel
        from gpytorch.likelihoods import GaussianLikelihood
        from gpytorch.means import ZeroMean
    except ImportError as error:
        return {"unavailable": str(error)}, None

    torch.manual_seed(0)
    dtype = torch.float64
    train_x = torch.tensor(x, dtype=dtype)
    # Negated: BoTorch maximizes.
    train_y = torch.tensor(-y, dtype=dtype).unsqueeze(-1)

    likelihood = GaussianLikelihood()
    likelihood.noise = torch.tensor(NOISE_VARIANCE, dtype=dtype)
    covar = ScaleKernel(RBFKernel())
    covar.base_kernel.lengthscale = torch.tensor(LENGTHSCALE, dtype=dtype)
    covar.outputscale = torch.tensor(SIGNAL_VARIANCE, dtype=dtype)

    model = SingleTaskGP(
        train_x, train_y,
        likelihood=likelihood,
        mean_module=ZeroMean(),
        covar_module=covar,
        outcome_transform=None,
        input_transform=None,
    )
    model.eval()

    query = torch.tensor(q, dtype=dtype)
    with torch.no_grad():
        posterior = model.posterior(query)
        mean = posterior.mean.squeeze(-1).numpy()
        sd = posterior.variance.clamp_min(0.0).sqrt().squeeze(-1).numpy()

        acquisition = ExpectedImprovement(model, best_f=float((-y).max()))
        ei = acquisition(query.unsqueeze(1)).numpy()

    # GPyTorch stores constrained parameters through a softplus whose inverse
    # is evaluated in single precision, so a float64 setter does *not* round
    # trip: asking for a lengthscale of 0.7 stores something that reads back
    # about 1.2e-8 away. Every reference therefore uses what GPyTorch actually
    # holds rather than what it was asked for. Tolerating the gap instead would
    # have meant loosening a correctness gate to accommodate a bug that is not
    # in FortBO.
    effective = {
        "lengthscale": float(covar.base_kernel.lengthscale.item()),
        "signal_variance": float(covar.outputscale.item()),
        "noise_variance": float(likelihood.noise.item()),
    }

    # Back to the minimization convention FortBO uses.
    return {
        "mean": (-mean).tolist(),
        "sd": sd.tolist(),
        "expected_improvement": ei.tolist(),
        "best": float(y.min()),
    }, effective


def jax_reference(x, y, q, lengthscale, signal_variance, noise) -> dict:
    """The same closed forms again, in JAX, at float64.

    JAX defaults to float32 and silently downcasts, which would produce a
    "disagreement" of about 1e-7 that says nothing about any implementation.
    x64 is enabled explicitly before any array is made, because the flag has no
    effect once tracing has begun.
    """
    try:
        import jax
        jax.config.update("jax_enable_x64", True)
        import jax.numpy as jnp
        from jax.scipy.special import erf as jerf
    except ImportError as error:
        return {"unavailable": str(error)}

    xj = jnp.asarray(x, dtype=jnp.float64)
    yj = jnp.asarray(y, dtype=jnp.float64)
    qj = jnp.asarray(q, dtype=jnp.float64)

    def kernel(a, b):
        squared = ((a[:, None, :] - b[None, :, :]) ** 2).sum(-1)
        return signal_variance * jnp.exp(-0.5 * squared / lengthscale**2)

    gram = kernel(xj, xj) + noise * jnp.eye(xj.shape[0], dtype=jnp.float64)
    factor = jnp.linalg.cholesky(gram)
    alpha = jax.scipy.linalg.solve_triangular(
        factor.T, jax.scipy.linalg.solve_triangular(factor, yj, lower=True),
        lower=False)

    cross = kernel(xj, qj)
    mean = cross.T @ alpha
    solved = jax.scipy.linalg.solve_triangular(factor, cross, lower=True)
    variance = jnp.clip(jnp.diag(kernel(qj, qj)) - (solved**2).sum(0), 0.0, None)
    sd = jnp.sqrt(variance)

    best = jnp.min(yj)
    gap = best - XI - mean
    z = jnp.where(sd > 0.0, gap / jnp.where(sd > 0.0, sd, 1.0), 0.0)
    cdf = 0.5 * (1.0 + jerf(z / math.sqrt(2.0)))
    pdf = jnp.exp(-0.5 * z**2) / math.sqrt(2.0 * math.pi)
    ei = jnp.where(sd > 0.0, gap * cdf + sd * pdf, jnp.maximum(gap, 0.0))

    return {
        "mean": np.asarray(mean).tolist(),
        "sd": np.asarray(sd).tolist(),
        "expected_improvement": np.asarray(ei).tolist(),
        "best": float(best),
        "dtype": str(mean.dtype),
    }


def main() -> int:
    x, y = training_set()
    q = query_set()

    reference, effective = botorch_reference(x, y, q)
    if effective is None:
        effective = {
            "lengthscale": LENGTHSCALE,
            "signal_variance": SIGNAL_VARIANCE,
            "noise_variance": NOISE_VARIANCE,
        }

    payload = {
        "note": (
            "Pinned model, not fitted. Fitting on each side would compare "
            "optimizers and report the difference as a modelling discrepancy."
        ),
        "lengthscale": effective["lengthscale"],
        "signal_variance": effective["signal_variance"],
        "noise_variance": effective["noise_variance"],
        "requested_lengthscale": LENGTHSCALE,
        "xi": XI,
        "precision": "float64",
        "train_x": x[:, 0].tolist(),
        "train_y": y.tolist(),
        "query": q[:, 0].tolist(),
        "numpy": numpy_reference(x, y, q, effective["lengthscale"],
                                 effective["signal_variance"],
                                 effective["noise_variance"]),
        "botorch": reference,
        "jax": jax_reference(x, y, q, effective["lengthscale"],
                             effective["signal_variance"],
                             effective["noise_variance"]),
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"wrote {OUTPUT}")
    write_fortran_fixture(payload)
    print(f"wrote {FORTRAN_OUTPUT}")

    if "unavailable" in reference:
        print("botorch unavailable:", reference["unavailable"])
        return 0

    # The two references must agree with each other before either is used as a
    # reference for anything. If they do not, the disagreement is between the
    # two of them and FortBO is not the thing to change.
    # Per-field tolerances, each with a reason. A single loose tolerance would
    # hide that the posterior agrees to machine precision while the acquisition
    # does not, which is the informative part.
    tolerances = {
        # The posterior is the same closed form on both sides and agrees to
        # rounding. Anything above this is a real modelling difference.
        "mean": 1e-12,
        "sd": 1e-12,
        # BoTorch's *legacy* analytic ExpectedImprovement has known numerics
        # issues -- it says so itself on import, citing arXiv:2310.20708, the
        # logEI paper which is in this repository's provenance. Measured here at
        # about 2e-9 against the direct algebra. JAX corroborates: it agrees
        # with NumPy at 4e-16 on the same quantity, so two independent
        # implementations land on the same answer and BoTorch alone departs
        # from it. FortBO's own logEI follows that paper, so where they
        # disagree at this magnitude BoTorch is the outlier, not FortBO.
        "expected_improvement": 1e-7,
    }
    failed = False
    jax_result = payload["jax"]
    if "unavailable" in jax_result:
        print("jax unavailable:", jax_result["unavailable"])
    else:
        # A float32 JAX would disagree at about 1e-7 and say nothing about any
        # implementation, so the dtype is asserted rather than assumed.
        if jax_result["dtype"] != "float64":
            print(f"  JAX ran at {jax_result['dtype']}, not float64")
            return 1
        for field in tolerances:
            worst = float(np.abs(np.array(payload["numpy"][field])
                                 - np.array(jax_result[field])).max())
            print(f"  numpy vs jax {field}: max |diff| = {worst:.3e}")
            if worst > tolerances[field]:
                print("  DISAGREEMENT between numpy and jax")
                failed = True

    for field, tolerance in tolerances.items():
        a = np.array(payload["numpy"][field])
        b = np.array(reference[field])
        worst = float(np.abs(a - b).max())
        print(f"  numpy vs botorch {field}: max |diff| = {worst:.3e} "
              f"(tolerance {tolerance:.0e})")
        if worst > tolerance:
            print("  DISAGREEMENT between the two references")
            failed = True
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
