#!/usr/bin/env python3
"""Record FortBO's TuRBO ordering results at budgets the test suite cannot run.

`fo` caps a slow test at five minutes. The paper's own candidate rule --
`min(100d, 5000)` per region per step -- means the rover and Ackley arms hit
that cap at budgets where a GP holds a couple of dozen points in sixty or two
hundred dimensions. That is not enough for a trust region to do anything an
undirected sweep does not, and the measurements bear it out: on rover-60 at 22
evaluations TuRBO-1 *loses* to random search, and at 60 evaluations it wins by
about twelve percent. The ordering is real; it just needs room.

So the expensive comparison runs here, where it can take as long as it needs,
and the result is committed as a fixture the test suite asserts against. That
is a weaker guarantee than a live run and is labelled as such: the test checks
a recorded benchmark, and the command that regenerates it is written into the
fixture so the number can never become folklore.

Every parameter is passed on the command line to `fortbo_bench_ordering`
rather than compiled in, so the budget a published number came from is visible
in the invocation that produced it.
"""

from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FORTBO = ROOT.parent / "fortbo"
OUTPUT = ROOT / "fixtures" / "fortbo_ordering.json"
FORTRAN_OUTPUT = FORTBO / "test" / "fixtures" / "fortbo_ordering.txt"

# Budgets chosen by measurement, not by preference: each is the smallest that
# lets the method separate from undirected search on that problem, which is
# the claim being tested. Smaller budgets were tried first and are recorded in
# the roadmap as the negative results they were.
RUNS = (
    # Budget 80 with three regions is where the paper's *full* ordering
    # appears: TuRBO-m ahead of TuRBO-1 ahead of random. At 22 evaluations
    # TuRBO-1 lost to random outright, and at 60 with one region it won but
    # said nothing about several regions. Both smaller runs are recorded in
    # the roadmap as the negative results they were.
    {"problem": "rover", "budget": 80, "n_initial": 8, "regions": 3, "seeds": 3},
    {"problem": "push", "budget": 90, "n_initial": 10, "regions": 3, "seeds": 3},
    {"problem": "ackley", "budget": 16, "n_initial": 5, "regions": 1, "seeds": 3},
)


def run_one(entry: dict) -> dict | None:
    command = [
        "fo", "exec", "fortbo_bench_ordering",
        entry["problem"], str(entry["budget"]), str(entry["n_initial"]),
        str(entry["regions"]), str(entry["seeds"]),
    ]
    started = time.perf_counter()
    completed = subprocess.run(
        command, cwd=FORTBO, capture_output=True, text=True, timeout=20000,
    )
    elapsed = time.perf_counter() - started
    if completed.returncode != 0:
        # Reported, not swallowed: a run that failed is a different fact from
        # one that ran badly.
        print(f"  {entry['problem']}: FAILED\n{completed.stdout[-800:]}")
        return None

    line = next(
        (l for l in completed.stdout.splitlines() if l.strip().startswith("RESULT")),
        None,
    )
    if line is None:
        print(f"  {entry['problem']}: no RESULT line")
        return None

    fields = line.split()
    # RESULT problem budget n_initial regions seeds turbo1 turbom random
    return {
        "problem": fields[1],
        "budget": int(fields[2]),
        "n_initial": int(fields[3]),
        "regions": int(fields[4]),
        "seeds": int(fields[5]),
        "turbo1": float(fields[6]),
        "turbom": float(fields[7]),
        "random": float(fields[8]),
        "wall_seconds": elapsed,
        "command": " ".join(command),
    }


def main() -> int:
    results = []
    for entry in RUNS:
        print(f"running {entry['problem']} at budget {entry['budget']} ...")
        result = run_one(entry)
        if result is None:
            continue
        results.append(result)
        beat = result["turbo1"] < result["random"]
        print(f"  turbo1 {result['turbo1']:.4f}  random {result['random']:.4f}"
              f"  -> {'beats' if beat else 'DOES NOT BEAT'} random")

    payload = {
        "note": (
            "FortBO's own TuRBO results at budgets the test suite cannot run "
            "inside fo's five-minute slow-test cap. The suite asserts against "
            "these recorded numbers; regenerate with this script."
        ),
        "results": results,
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"wrote {OUTPUT}")

    lines = [
        "# Generated by fortbo-bench/scripts/record_fortbo_ordering.py.",
        "# FortBO's TuRBO results at budgets beyond the slow-test cap.",
        "# Regenerate with that script; do not hand-edit.",
        "# count",
        f"{len(results)}",
        "# problem budget regions turbo1 turbom random",
    ]
    for result in results:
        lines.append(
            f"{result['problem']} {result['budget']} {result['regions']} "
            f"{result['turbo1']!r} {result['turbom']!r} {result['random']!r}"
        )
    FORTRAN_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    FORTRAN_OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {FORTRAN_OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
